fn main() {
    #[cfg(feature = "tauri-app")]
    {
        if std::env::var("CARGO_FEATURE_TAURI_APP").is_ok() {
            emit_oclive_invoke_handler_gen();
            tauri_build::build();
            emit_invoke_capability_ts();
        }
    }

    #[cfg(not(feature = "tauri-app"))]
    {
        // No-op build script for non-Tauri builds.
    }
}

#[cfg(feature = "tauri-app")]
fn cargo_feature_enabled(name: &str) -> bool {
    let key = format!("CARGO_FEATURE_{}", name.to_uppercase().replace('-', "_"));
    std::env::var_os(&key).is_some()
}

#[cfg(feature = "tauri-app")]
fn read_path_list(rel: &str) -> Vec<String> {
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let path = manifest_dir.join(rel);
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("failed to read invoke list {:?}: {}", path, e);
    });
    raw.lines()
        .map(|l| l.trim().to_string())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect()
}

#[cfg(feature = "tauri-app")]
fn emit_oclive_invoke_handler_gen() {
    let out_dir = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let mut paths = read_path_list("invoke_lists/core.txt");
    if cargo_feature_enabled("invoke-agent") {
        paths.extend(read_path_list("invoke_lists/agent.txt"));
    }
    if cargo_feature_enabled("invoke-expert-models") {
        paths.extend(read_path_list("invoke_lists/expert_models.txt"));
    }
    if cargo_feature_enabled("invoke-role-market") {
        paths.extend(read_path_list("invoke_lists/role_market.txt"));
    }
    if cargo_feature_enabled("invoke-plugin-market") {
        paths.extend(read_path_list("invoke_lists/plugin_market.txt"));
    }
    if cargo_feature_enabled("invoke-plugin-creator") {
        paths.extend(read_path_list("invoke_lists/plugin_creator.txt"));
    }

    let body = paths.join(",\n            ");
    let gen = format!(
        r#"macro_rules! oclive_invoke_handler {{
    () => {{
        tauri::generate_handler![
            {body}
        ]
    }};
}}
"#,
        body = body
    );

    let gen_path = out_dir.join("oclive_invoke_handler_gen.rs");
    std::fs::write(&gen_path, gen).unwrap_or_else(|e| {
        panic!("failed to write {:?}: {}", gen_path, e);
    });
}

/// Keeps Vue `invoke` guards aligned with the desktop crate's `invoke-*` features.
#[cfg(feature = "tauri-app")]
fn emit_invoke_capability_ts() {
    let agent = cargo_feature_enabled("invoke-agent");
    let expert_models = cargo_feature_enabled("invoke-expert-models");
    let role_market = cargo_feature_enabled("invoke-role-market");
    let plugin_market = cargo_feature_enabled("invoke-plugin-market");
    let plugin_creator = cargo_feature_enabled("invoke-plugin-creator");

    let out = format!(
        r"// AUTO-GENERATED by `oclivenewnew-tauri/build.rs` from active Cargo features.
// Regenerated on each `cargo build` / `cargo check` of this crate with `tauri-app` enabled.
// Keys mirror `src-tauri/invoke_lists/` and `src/lib/tauriInvokeCapabilities.ts`.

export const TAURI_INVOKE_CAPABILITIES = {{
  agent: {agent},
  expertModels: {expert_models},
  roleMarket: {role_market},
  pluginMarket: {plugin_market},
  pluginCreator: {plugin_creator},
}} as const;

export type TauriInvokeCapabilityKey = keyof typeof TAURI_INVOKE_CAPABILITIES;
",
        agent = agent,
        expert_models = expert_models,
        role_market = role_market,
        plugin_market = plugin_market,
        plugin_creator = plugin_creator,
    );

    let path = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .join("../src/gen/tauri-invoke-capabilities.ts");
    if let Some(dir) = path.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    if let Err(e) = std::fs::write(&path, out) {
        println!("cargo:warning=failed to write {:?}: {}", path, e);
    }
}
