//! `oclive ci` — 生成与检查 GitHub Actions CI。

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
pub struct CiCli {
    #[command(subcommand)]
    pub command: CiCommands,
}

#[derive(Subcommand, Debug)]
pub enum CiCommands {
    /// 生成 `.github/workflows/ci.yml`
    Init(CiInitArgs),
    /// 检查 CI 是否与最新模板一致
    Check(CiCheckArgs),
}

#[derive(Parser, Debug)]
pub struct CiInitArgs {
    #[arg(short = 'o', long, default_value = ".")]
    pub path: PathBuf,
    #[arg(long)]
    pub force: bool,
}

#[derive(Parser, Debug)]
pub struct CiCheckArgs {
    #[arg(short = 'o', long, default_value = ".")]
    pub path: PathBuf,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum ProjectCiKind {
    KernelServer,
    Library,
}

pub fn run(cli: CiCli) -> Result<()> {
    match cli.command {
        CiCommands::Init(a) => run_init(a),
        CiCommands::Check(a) => run_check(a),
    }
}

fn run_init(args: CiInitArgs) -> Result<()> {
    let root = args.path.canonicalize().context("path")?;
    let kind = detect_project_kind(&root)?;
    let workflow = root.join(".github/workflows/ci.yml");
    if workflow.is_file() && !args.force {
        bail!(
            "已存在 {}；使用 --force 覆盖",
            workflow.display()
        );
    }
    fs::create_dir_all(workflow.parent().unwrap()).context("mkdir .github/workflows")?;
    let content = render_ci_yaml(kind);
    fs::write(&workflow, content).context("write ci.yml")?;
    println!("已生成 {}（{:?}）", workflow.display(), kind);
    Ok(())
}

fn run_check(args: CiCheckArgs) -> Result<()> {
    let root = args.path.canonicalize().context("path")?;
    let kind = detect_project_kind(&root)?;
    let workflow = root.join(".github/workflows/ci.yml");
    if !workflow.is_file() {
        bail!("缺少 {}；请运行 oclive ci init", workflow.display());
    }
    let current = fs::read_to_string(&workflow)?;
    let expected = render_ci_yaml(kind);
    if current.trim() == expected.trim() {
        println!("✅ CI 配置与 oclive 最新模板一致");
        Ok(())
    } else {
        println!("⚠️ CI 配置与模板不一致；运行 `oclive ci init --force` 更新");
        std::process::exit(1);
    }
}

fn detect_project_kind(root: &Path) -> Result<ProjectCiKind> {
    let cargo = root.join("Cargo.toml");
    if !cargo.is_file() {
        bail!("缺少 Cargo.toml");
    }
    let raw = fs::read_to_string(&cargo)?;
    let v: toml::Value = toml::from_str(&raw)?;
    let has_main = root.join("src/main.rs").is_file()
        || root.join("src/main_monolith.rs").is_file();
    let bins = v
        .get("bin")
        .and_then(|b| b.as_array())
        .map(|a| !a.is_empty())
        .unwrap_or(false);
    if has_main || bins {
        Ok(ProjectCiKind::KernelServer)
    } else {
        Ok(ProjectCiKind::Library)
    }
}

fn render_ci_yaml(kind: ProjectCiKind) -> String {
    let oocp_job = if kind == ProjectCiKind::KernelServer {
        r#"
  bench-regression:
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: bench regression gate
        run: |
          cargo build -p oclive-cli --release 2>/dev/null || cargo build -p oclive-cli
          cargo run -p oclive-cli -- bench --release -o . --runs 3 --save || true
          cargo run -p oclive-cli -- bench --release -o . --regression --runs 5 || true
        continue-on-error: true

  oocp:
    runs-on: ubuntu-latest
    needs: [build-test]
    if: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: dtolnay/rust-toolchain@stable
      - name: OOCP test suite (enable when kernel linked to oclivenewnew)
        run: echo "skipped — link --kernel-source in scaffold to enable"
"#
    } else {
        ""
    };

    let extra_steps = if kind == ProjectCiKind::KernelServer {
        r#"
      - name: oclive test
        run: cargo run -p oclive-cli -- test -o . --skip-oocp
        continue-on-error: true
"#
    } else {
        ""
    };

    format!(
        r#"# Generated by oclive ci init — review before enabling OOCP / registry secrets.
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

env:
  OCLIVE_REGISTRY_URL: ${{{{ vars.OCLIVE_REGISTRY_URL }}}}
  OCLIVE_MARKET_INDEX_URL: ${{{{ vars.OCLIVE_MARKET_INDEX_URL }}}}
  OCLIVE_PLUGIN_INDEX_URL: ${{{{ vars.OCLIVE_PLUGIN_INDEX_URL }}}}
  OCLIVE_HTTP_API_MOCK_LLM: "1"

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{{{ matrix.os }}}}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: cargo build
        run: cargo build --release
      - name: cargo test
        run: cargo test
{extra_steps}
{oocp_job}
"#
    )
}
