//! Execute a developer consumer through the library actually generated by CLI.
//! Run explicitly with diagnostics-host; the default CLI stays SQLite-free.

#![cfg(feature = "diagnostics-host")]

mod common;

use std::fs;
use std::process::Command;

#[test]
fn generated_library_runs_minimal_text_and_keeps_rich_entry() {
    let temp = tempfile::tempdir().expect("isolated generated library");
    let project = temp.path().join("library-consumer");
    let root = common::repo_root();
    let init = common::run_cli_output(&[
        "init",
        "--non-interactive",
        "--quiet",
        "--template",
        "library-embed",
        "--project-name",
        "minimal-consumer",
        "--kernel-source",
        root.to_str().expect("repo path"),
        "-o",
        project.to_str().expect("output path"),
    ]);
    assert!(init.status.success(), "CLI init: {init:?}");
    // Reuse the workspace's resolved versions rather than whichever versions
    // happen to be newest in this machine's offline cache. Cargo adds only the
    // generated root package to this isolated lockfile.
    fs::copy(root.join("Cargo.lock"), project.join("Cargo.lock"))
        .expect("seed consumer dependency versions");
    let manifest = project.join("Cargo.toml");
    let mut cargo = fs::read_to_string(&manifest).expect("generated manifest");
    // These belong to the isolated test consumer, not the generated library.
    cargo.push_str(
        "\n[dev-dependencies]\nasync-trait = \"0.1\"\ntokio = { version = \"1\", features = [\"rt\"] }\n",
    );
    fs::write(&manifest, cargo).expect("test-only dependencies");
    fs::create_dir(project.join("tests")).expect("consumer tests");
    fs::write(
        project.join("tests/consumer.rs"),
        include_str!("fixtures/minimal_role_library_consumer.rs"),
    )
    .expect("consumer fixture");
    let result = Command::new("cargo")
        // Read the repository Cargo config and reuse its external target/cache.
        .current_dir(&root)
        .args(["test", "--offline", "--manifest-path"])
        .arg(&manifest)
        .env("OCLIVE_LIBRARY_FIXTURE_DATA", project.join("fixture-data"))
        .output()
        .expect("consumer Cargo test");
    let stdout = String::from_utf8_lossy(&result.stdout);
    let stderr = String::from_utf8_lossy(&result.stderr);
    print!("{stdout}");
    eprint!("{stderr}");
    assert!(result.status.success(), "consumer exit: {}", result.status);
    assert!(stdout.contains("developer_converter_uses_generated_public_surface ... ok"));
    assert!(stderr.contains("Doc-tests minimal_consumer"));
    assert_eq!(
        stdout
            .matches("test result: ok. 1 passed; 0 failed")
            .count(),
        2,
        "one consumer test and one compiled rustdoc example"
    );
    // The child has exited, releasing all SQLite handles before explicit cleanup.
    temp.close()
        .expect("remove generated project and fixture DB");
}
